name = "guiaparamolderiaysastreria"
compatibility_date = "2023-12-01"

[build]
command = "npm run build"

[site]
bucket = ".next"

[env.production]
workers_dev = true

[build.upload]
format = "service-worker"