name = "guiaparamolderiaysastreria"
compatibility_date = "2025-03-21"

[build]
command = "npm run build"

[pages]
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat"]